### ISSUE TITLE
Set up project structure and initialize backend and frontend folders

### ISSUE THREAD

**Issue by Archisha-Dhyani** [upes-open/OSoC-MeetingMinutes-MOM-Generator#1]
Create a folder structure for the project and initialize the backend and frontend with the required configuration files.

**Comment by mswat5** [comment]
hey @Archisha-Dhyani can you assign it to me?

**Comment by Archisha-Dhyani** [comment]
hey, @mswat5 , the issue has been assigned to you.

**Comment by virajp4** [comment]
hey, can i work on this?

**Comment by Archisha-Dhyani** [comment]
Sure!
