### ISSUE TITLE
Write Unit Tests for Backend Functionality

### ISSUE THREAD

**Issue by Archisha-Dhyani** [upes-open/OSoC-MeetingMinutes-MOM-Generator#10]
Develop a comprehensive set of unit tests to ensure the reliability and correctness of the backend functionality.

**Comment by vasanthanb** [comment]
I need some discription about the issue

**Comment by Archisha-Dhyani** [comment]
Okay, so this is something we need to do to test the accuracy once our ML model is created. You'll have to prepare test cases using different testing frameworks. Since the ML model has not yet been made we won't be able to test them as of now, but you can research and prepare maybe basic test cases that'll help us in the future. But again we won't be able to check if it's working or not. Till then you can check out other issues if you want. Thanks for showing interest.
