### ISSUE TITLE
Extracting audio from meetings

### ISSUE THREAD

**Issue by Archisha-Dhyani** [upes-open/OSoC-MeetingMinutes-MOM-Generator#11]
Figure out a method that will extract audio from the live meeting video and save it in mp3 format

**Comment by aman-agarwal-0205** [comment]
i want to work on this issue

**Comment by Archisha-Dhyani** [comment]
Sure, I'll assign you the issue.

**Comment by Archisha-Dhyani** [comment]
hey @aman-agarwal-0205 any updates or problems faced regarding the issue ?

**Comment by aman-agarwal-0205** [comment]
I apologise for not starting with the tasks. I had food poisoning last
week, and was hospitalised for 4 days. I will start working on the issues
right away.

**Comment by Archisha-Dhyani** [comment]
Thank you for informing me about your situation. I hope you're feeling better now. Take your time to recover fully, and once you're ready, we can discuss how to proceed with the tasks.

**Comment by aman-agarwal-0205** [comment]
Thank you. I have started to work on it. Currently I am working on
gathering the dataset.

**Comment by Archisha-Dhyani** [comment]
Good going.

**Comment by virajp4** [comment]
can i work on this?

**Comment by Archisha-Dhyani** [comment]
Sure.
