### ISSUE TITLE
Create logo for extension

### ISSUE THREAD

**Issue by Archisha-Dhyani** [upes-open/OSoC-MeetingMinutes-MOM-Generator#12]

**Comment by virajp4** [comment]
I would like to work on this. Are there any specifications that you would like to include in the logo?

**Comment by Archisha-Dhyani** [comment]
Sure @virajp4 , I'll assign you the issue. As of now there are no specifications, the logo should be just something that resonates with the functionality of this extension. Moreover. you can send the designs on the discord workspace and we'll have further discussions over there.

**Comment by ArshdeepKaur04** [comment]
I would also like to contribute to this issue. Kindly assign me this issue.

**Comment by Archisha-Dhyani** [comment]
Hey Arshdeep,thanks for showing interest.I appreciate the enthusiasm but this issue is almost completed. Check out some other issues that grab your interest and then let me know, I'll assign them to you.
