### ISSUE TITLE
Data collection and preprocessing

### ISSUE THREAD

**Issue by Archisha-Dhyani** [upes-open/OSoC-MeetingMinutes-MOM-Generator#13]
Identify and gather publicly available datasets for transcribed meeting recordings and corresponding MOMs. 
Clean the collected data by removing irrelevant information.

**Comment by aman-agarwal-0205** [comment]
I want to work on this issue

**Comment by Archisha-Dhyani** [comment]
Sure , I'll assign you the issue.

**Comment by aman-agarwal-0205** [comment]
Hi. I've been looking for datasets with transcribed meeting recordings and corresponding MOMs but such datasets are unavailable. I am able to find meeting recordings but it does not contain MOMs. How should I proceed?

**Comment by Archisha-Dhyani** [comment]
Hi Aman, Can you share the datasets with me, preferably on discord and we can have further discussions after that?

**Comment by virajp4** [comment]
hey, I would like to help resolve this issue

**Comment by Archisha-Dhyani** [comment]
Sure, the issue has been assigned to you.
