### ISSUE TITLE
Create a basic HTML/CSS frontend layout

### ISSUE THREAD

**Issue by Archisha-Dhyani** [upes-open/OSoC-MeetingMinutes-MOM-Generator#2]
Develop a simple frontend layout for extension page.

**Comment by Shivansh175** [comment]
I would love to take up this issue. But can u please elaborate it a bit more.

**Comment by Archisha-Dhyani** [comment]
@Shivansh175  Sure, so basically whenever you add any chrome extension you see a page in which details of the extension are given and there is an option to add that extension to chrome . So you'll have to develop a layout for that. Let me know if its clear and if you'll be working on the issue.

**Comment by Shivansh175** [comment]
Okay, Please assign me this issue.

**Comment by Archisha-Dhyani** [comment]
sure

**Comment by Archisha-Dhyani** [comment]
hey @Shivansh175 , I've added the boiler plate kindly refer to it in case of any doubt.

**Comment by Archisha-Dhyani** [comment]
hey @Shivansh175 hope you have joined the MeetingMinutes workspace on discord. You can do that by assigning yourself the MeetingMinutes project under osoc-projects. Check out other issues as well where you think you can contribute and feel free to reach me out in case of any doubt.

**Comment by Shivansh175** [comment]
sure

**Comment by Shivansh175** [comment]
I couldn't start working on this project due to some of my doubts...
1. Do I have to make this UI as that of other famous chrome extensions?
2. If yes, then how much frontend of it I have to build?
3. What content I have to display there?

**Comment by Archisha-Dhyani** [comment]
@Shivansh175  It'll be great if you ping me on the MeetingMinutes workspace on discord. I'll clear all your doubts. it'll be easier for me explain everything over there.

**Comment by virajp4** [comment]
hello, can i work on this issue too?

**Comment by Archisha-Dhyani** [comment]
sure. @virajp4 , I'll assign you the issue. While working on this issue use the boiler plate code provided. Kindly ask me any further doubts on the discord workspace.
