### ISSUE TITLE
MOM Generation Model - Implement a model for generating MOMs from meeting transcripts.

### ISSUE THREAD

**Issue by Archisha-Dhyani** [upes-open/OSoC-MeetingMinutes-MOM-Generator#4]
Select an appropriate NLP model for MOM generation

**Comment by avnigoyal25** [comment]
Hey can you explain a bit about this issue?

**Comment by Archisha-Dhyani** [comment]
Sure, 
See in this issue first you'll have to decide the format and structure of the MOM that you want the model to generate
then Choose a suitable NLP model for text generation. Train an ML model where the meeting transcripts are used as input, and the MOMs are used as output.

Let me know if you want me to assign this issue to you. You can do the research you want, and if you get stuck somewhere I'm always here to help.

**Comment by avnigoyal25** [comment]
i want to discuss about it more

**Comment by Charu-2718** [comment]
Can I work on this issue?

**Comment by Archisha-Dhyani** [comment]
Sure!

**Comment by Archisha-Dhyani** [comment]
@avnigoyal25 Sure, we can discuss more about it. I'll schedule a meeting soon. There we can have further discussions. Kindly check the project workspace on discord for further updates.

**Comment by virajp4** [comment]
i would like to work on this issue.

**Comment by Archisha-Dhyani** [comment]
Sure.
