### ISSUE TITLE
Develop a language identification and conversion model.

### ISSUE THREAD

**Issue by Archisha-Dhyani** [upes-open/OSoC-MeetingMinutes-MOM-Generator#5]
Model to detect languages in meeting transcripts and translate it to English. The model should be able to detect languages in multilingual meetings and convert it to English.

**Comment by 1416harshika** [comment]
would be intrested ro work on this

**Comment by Archisha-Dhyani** [comment]
Sure, I'll assign you the issue

**Comment by Archisha-Dhyani** [comment]
hey @1416harshika , any updates?

**Comment by avnigoyal25** [comment]
i want to work on this issue
