### ISSUE TITLE
Implement user authentication and authorization

### ISSUE THREAD

**Issue by Archisha-Dhyani** [upes-open/OSoC-MeetingMinutes-MOM-Generator#8]

**Comment by 1416harshika** [comment]
i would like to work on this

**Comment by avnigoyal25** [comment]
Can you explain about this issue?

**Comment by Archisha-Dhyani** [comment]
In this you'll have to verify who the user is and the access in general. You can look up authentication and authorization and if you still face any issue, feel free to ask me.
